import "./globals.css";
import { headers } from "next/headers";
import ClientThemeWrapper from "@/components/ClientThemeWrapper";
import MobileView from "@/components/MobileView";

export const metadata = {
  title: "Gabriel Raguindin Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const userAgent = (await headers()).get('user-agent') || '';
  const isMobile = /Android|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i.test(userAgent);
  
  return (
    <html lang="en">
      <head>

      </head>
      <body>
        {isMobile ? <MobileView /> :
          <ClientThemeWrapper>{children}</ClientThemeWrapper>
        }
      </body>
    </html>
  );
}
